export default function Footer() {
  return (
    <footer className="relative z-10 border-t border-white/5 px-6 py-10">
      <div className="mx-auto flex max-w-5xl flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
        <p className="font-mono text-xs text-ink-faint">
          Loss<span className="text-signal">Landscape</span> — every terrain, chart, and icon on
          this page is generated by code, not stock imagery.
        </p>
        <a
          href="#hero"
          className="font-mono text-xs text-ink-faint underline decoration-white/20 underline-offset-4 transition-colors hover:text-signal"
        >
          back to the top ↑
        </a>
      </div>
    </footer>
  );
}
